### DISCUSSION TITLE
How to use Media Query with CreateStyles

### DISCUSSION THREAD

**Discussion by kimfucious** [mantinedev/mantine#3040] [Q&A] [answered]
Hi there,

There's a bug in Safari that causes an issue when using next/image v.13.

There's a work around for it, but I'm having a hard time wrapping my head around how to do this with `createStyles`.

The CSS workaround is:
```css
@media not all and (min-resolution:.001dpcm) {
  img[loading="lazy"] {
    clip-path: inset(0.5px);
  }
}
```
I've tried the following, but I'm obviously flailing about and confused by the syntax:
```js
const useStyles = createStyles((theme) => ({
    ["@media not all and (max-resolution: .001.dpcm"]: {
        [img[ loading="lazy" ]]: { // <= stuck here
          clipPath: "inset(0.5px) "
        },
      },
}));
```
Any help would be most appreciated.
