### DISCUSSION TITLE
Option to adjust rem

### DISCUSSION THREAD

**Discussion by disillusionedowl** [mantinedev/mantine#3826] [Feature requests]
Since Mantine can also be used as drop-in inside existing websites, it would be nice to have an option to adjust rem values for the Mantine scope (in theme object).

The current native way does not integrate well with websites that have crazy (or even just not very "rem optimized") base styles and for some reason cannot be changed, example:

```css
html {
  font-size: 1px; /* bad under the hood */
}
body {
  font-size: 99px; /* bad under the hood */
}
p, p.normal-text {
  font-size: 17px; /* end result still looking good though */
}
```

Proposed option:

```ts
remFontSizes: Record<'xs' | 'sm' | 'md' | 'lg' | 'xl', string>;
```

I saw other Discussions on this and still think it makes sense to have something like this in. On the other hand, the extra logic required would probably be a lot of bloat, so yeah...
Anyway, here it is in it's own thread, in a more straightforward problem/solution format to perhaps entice some further discussion.
