### DISCUSSION TITLE
How can I disable cursor pointer for everything?

### DISCUSSION THREAD

**Discussion by tx46** [mantinedev/mantine#4035] [Q&A] [answered]
I want everything to have the default cursor, except for text fields, etc. No hand pointers, please. What do I do?

**Comment by rtivital** [comment]
`* { cursor: default !important; }`

**Comment by tx46** [comment]
I tried that, but it changes the cursor on textboxes from the beam cursor to the default one, which is not right. I just want the hand to turn into the arrow.

**Reply by rtivital** [reply, marked as answer]
`* { cursor: default !important; } input { cursor: text !important! }`

**Comment by tx46** [comment]
To make it work properly:

```css
* {
  cursor: default !important;
}

input[type="password"],
input[type="text"],
textarea {
  cursor: text !important;
}
```
