### DISCUSSION TITLE
Inline Style variables - V7

### DISCUSSION THREAD

**Discussion by rodeyseijkens** [mantinedev/mantine#4418] [Feedback]
So I started to tinker with v7, I wondered if there was a way to better handle style overwrites in a css-module.
Because of the inline-style variables I can't easily overwite for example the `--button-hover`.

```css
.root {
  font-weight: 400;
  ...

  /* The only way to overwrite the variables is with !important */
  --button-hover: linear-gradient(35deg, var(--mantine-color-violet-9), var(--mantine-color-pink-7)) !important;
}
```

```tsx
<Button classNames={{ root: classes.root }}>Text</Button>
```
Also because the `.mantine-c33yiTy:hover:not([data-loading]):not(:disabled):not([data-disabled])` css specificity is a pain in the ass to overwrite.

**Comment by rtivital** [comment]
Override styles instead of CSS variables:

```css
.root {
  &:hover {
    background: red;
  }
}
```
