### DISCUSSION TITLE
Mantine breakpoint variable worked but got annoyed error in vscode

### DISCUSSION THREAD

**Discussion by idindrakusuma** [mantinedev/mantine#5296] [Q&A] [answered]
Hi guys! Firstly, thank you for creating this awesome UI library! very appreciate it!

I wanna ask question. 

I have CSS code like this and this is worked.
```css
/* File: style.module.css  */
.bottom_navigation {
  display: none;

  @media (max-width: $mantine-breakpoint-xs)  {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 16px;
    position: fixed;
    bottom: 0;
    width: 100%;
    border-top: calc(0.0625rem * var(--mantine-scale)) solid var(--mantine-color-gray-2);
  }
}

```

And this is my `postcss.config.js`
```js
// File: postcss.config.js
module.exports = {
  plugins: {
    'postcss-preset-mantine': {},
    'postcss-simple-vars': {
      variables: {
        'mantine-breakpoint-xs': '36em',
        'mantine-breakpoint-sm': '48em',
        'mantine-breakpoint-md': '62em',
        'mantine-breakpoint-lg': '75em',
        'mantine-breakpoint-xl': '88em',
      },
    },
  },
};


```

But I got error message like this in VScode

<img width="646" alt="image" src="https://github.com/mantinedev/mantine/assets/10141928/29a8883d-c957-484c-a61d-100421b3497e">

it isn't very pleasant. is it expected or any something I missed? Thanks!
