### DISCUSSION TITLE
Use theme.fn.lighten in MantineUI V7

### DISCUSSION THREAD

**Discussion by ecatugy** [mantinedev/mantine#5433] [Feature requests]
I use the following piece of code in CSS/JS:

```css
link {
    display: 'block';
    lineHeight: 1;
    padding: '8px 12px';
    borderRadius: theme.radius.sm;
    textDecoration: 'none';
    color: theme.white;
    fontSize: theme.fontSizes.sm;
    fontWeight: 500;

    '&:hover': {
        backgroundColor: theme.fn.lighten(
            (theme.fn.variant({ variant: 'filled', color: theme.primaryColor }).background as any),
            0
        );
    }
}
```

However, I couldn't find anything in the new documentation on how to migrate. Migrating to MantineUI 7 is a real struggle, which is why many people are giving up on using the framework. It's quite challenging.
