### DISCUSSION TITLE
Convert ActionIcon V6 to V7

### DISCUSSION THREAD

**Discussion by ecatugy** [mantinedev/mantine#5476] [Feature requests]
I'm currently struggling to migrate from Mantine V6 to V7. They've completely changed the behavior of the components when transitioning from CSSJS to CSS, breaking the entire layout. My current issue is with the ActionIcon component.

Here's the TypeScript/CSSJS in V6 code:

```typescript
return (
  <div
    key={node?.id}
    style={containerStyle}
    className={cx(classes.container, { [classes.active]: data.isSelected })}
  >
    <div className={classes.head}>
      <Text style={{ top: 0 }}>Container {id}</Text>
      {id !== '1' && (
        <ActionIcon className={classes.buttonTrash} onClick={handleRemoveNodeAsync}>
          <IconTrash size="1rem" />
        </ActionIcon>
      )}
    </div>
    {id !== '1' && (
      <div className={classes.handleTarget}>
        <Handle type="target" position={Position.Left} id={`${id}-in`} />
      </div>
    )}
    <div className={classes.handleSource}>
      <Handle type="source" position={Position.Right} id={`${id}-out`} />
    </div>
  </div>
)
```
CSSJS

```css
  buttonTrash: {
    color: theme.colorScheme === 'dark' ?  theme.colors.gray[5] :theme.colors.gray[7]  ,
    position: 'absolute',
    top: -3,
    right: -50,
    paddingTop: 5,
    '&:hover': {
      backgroundColor: 'transparent',
      transform: 'scale(1.35)',
    },
  },
```

Upon migrating to Mantine V7, it’s no longer possible to set it through the class because it doesn’t pick up the CSS. Here’s what I did

```typescript
  return (
    <div
      key={node?.id}
      style={containerStyle}
      className={cx(classes.container, { [classes.active]: data.isSelected })}
    >
      <div className={classes.head}>
        <Text style={{ top: 0 }}>Container {id}</Text>
        {id !== '1' && (
          <ActionIcon className={classes.buttonTrash} onClick={handleRemoveNodeAsync}>
            <IconTrash size="1rem" />
          </ActionIcon>
        )}
      </div>
      {id !== '1' && (
        <div className={classes.handleTarget}>
          <Handle type="target" position={Position.Left} id={`${id}-in`} />
        </div>
      )}
      <div className={classes.handleSource}>
        <Handle type="source" position={Position.Right} id={`${id}-out`} />
      </div>
    </div>
  )
}
```
CSS
```css
.buttonTrash {
  background-color: light-dark(var(--mantine-color-gray-5)), var(--mantine-color-gray-7);
  position: absolute;
  top: -3 !important;
  right: -100 !important;
  padding-top: 50 !important;
}

.buttonTrash:hover {
  background-color: transparent;
  transform: scale(1.35);
}
```

Has anyone else experienced this during the conversion? I’ve tried everything and it’s not possible to achieve the same effect, the ActionIcon component in version V7 no longer accepts absolute position.
