### DISCUSSION TITLE
How to set dynamic styles for a component in the theme?

### DISCUSSION THREAD

**Discussion by elibroftw** [mantinedev/mantine#5486] [Q&A]
I want to set the background of the Segmented Control to the following everywhere by default. How do I go about it? I know it's somewhere in the theme's components, but how do I make it dynamic based on the color scheme? I am calling the `<ColorSchemeScript defaultColorScheme='auto' />` in the same component that I'm setting the theme in.

```css
.segmentedControl {
    background-color: light-dark(var(--mantine-color-gray-2), var(--mantine-color-dark-9));
}
```
