### DISCUSSION TITLE
are responsive tables like react-super-responsive-table possible with mantine?

### DISCUSSION THREAD

**Discussion by jdion84** [mantinedev/mantine#5533] [Q&A]
i am interested in using mantine for all future projects, i absolutely love all of the possibilities

one thing im looking for in a ui lib is super responsive tables, similar to this: https://github.com/coston/react-super-responsive-table

take a look at the gif, the table cells basically turn into divs on mobile

is this possible with mantine?

**Comment by rtivital** [comment]
No, this feature is not supported

**Comment by Toshinaki** [comment]
It's basically css with media query.

Not verified but customizing table styles as `react-super-responsive-table` does could achieve what you want.

This is taken from devtools.
```css
@media screen and (max-width: 40em)
.responsiveTable td .tdBefore, .responsiveTable td.pivoted {
    text-align: left!important;
    white-space: pre-wrap;
    overflow-wrap: break-word;
}
```
