### DISCUSSION TITLE
Animate Tabs

### DISCUSSION THREAD

**Discussion by Camsteack** [mantinedev/mantine#5814] [Q&A]
Hi,
I am trying to add an animation on the `Tabs` component when changing tabs, to animate the selected tab indicator moving from in tab to another in the same way you would have on MUI for example.
I haven't been able to achieve that so I was wondering if anyone had tried and would be able to help.

Many thanks !

**Comment by rtivital** [comment]
Mantine does not support this feature. If you need it, you can implement that in your application by defining a custom Tabs variant. You can also use SegmentedControl component.

**Reply by Camsteack** [reply]
Hi @rtivital !
I knew it was not supported out of the box by Mantine but I'm wondering if someone had done it using a custom variant and could provide guidance or an example on how to do it :)

**Comment by tombohub** [comment]
Maybe if you say what did you try we can think some solution. 


To move like mui is little bit more complicated. You can create an illusion of movement by delaying removing of bottom border on non active tab, but appear immediately on active like amplify ui does: https://ui.docs.amplify.aws/react/components/tabs.



I didn't try but tab sets `data-active="true"` when tab becomes active. I am writing on top of my head please see if something like this works:

```css
.mantine-Tabs-tab {
transition: all 250ms; // make transition default for the disappear of bottom border
}

.mantine-Tabs-tab[data-active="true"] {
transition-property: none; // disable transition so it appears immediately on active tab
}
```
