### DISCUSSION TITLE
Reorganize the design tokens.

### DISCUSSION THREAD

**Discussion by tombohub** [mantinedev/mantine#5818] [Feature requests]
Currently component tier design tokens are defined inside css classes for each component.
This way component design tokens overwrite anything we define in :root.

I think it would be easier to customize Mantine if either:

1. component tier design tokens are removed like it's done in Fluent ui. They only use theme tier design tokens to style components: https://react.fluentui.dev/?path=/docs/theme-border-radii--page

```css
.r1alrhcs {
    align-items: center;
    box-sizing: border-box;
    display: inline-flex;
    justify-content: center;
    text-decoration-line: none;
    vertical-align: middle;
    margin: 0px;
    overflow: hidden;
    background-color: var(--colorNeutralBackground1);
    color: var(--colorNeutralForeground1);
    border: var(--strokeWidthThin) solid var(--colorNeutralStroke1);
    font-family: var(--fontFamilyBase);
    outline-style: none;
    padding: 5px var(--spacingHorizontalM);
    min-width: 96px;
    border-radius: var(--borderRadiusMedium);
    font-size: var(--fontSizeBase300);
    font-weight: var(--fontWeightSemibold);
    line-height: var(--lineHeightBase300);
    transition-duration: var(--durationFaster);
    transition-property: background, border, color;
    transition-timing-function: var(--curveEasyEase);
}
```

2. have all component tokens together in :root and use them in component styling. Amplify ui does that by defining `--internal-button-height: var(--button-height)` in component class and then `button-height: var(--internal-button-height)`: https://ui.docs.amplify.aws/react/theming/css-variables:

```css
.amplify-button {
    --amplify-internal-button-background-color: var(--amplify-components-button-background-color);
    --amplify-internal-button-border-color: var(--amplify-components-button-border-color);
    --amplify-internal-button-color: var(--amplify-components-button-color);
    --amplify-internal-button-focus-box-shadow: var(--amplify-components-button-focus-box-shadow);
    --amplify-internal-button-border-width: var(--amplify-components-button-border-width);
    align-items: center;
    background-color: var(--amplify-internal-button-background-color);
    border-color: var(--amplify-internal-button-border-color);
    border-radius: var(--amplify-components-button-border-radius);
    border-style: var(--amplify-components-button-border-style);
    border-width: var(--amplify-internal-button-border-width);
    box-sizing: border-box;
    color: var(--amplify-internal-button-color);
    cursor: pointer;
    display: inline-flex;
    font-size: var(--amplify-components-button-font-size);
    font-weight: var(--amplify-components-button-font-weight);
    justify-content: center;
    line-height: var(--amplify-components-button-line-height);
    padding-block-start: var(--amplify-components-button-padding-block-start);
    padding-block-end: var(--amplify-components-button-padding-block-end);
    padding-inline-start: var(--amplify-components-button-padding-inline-start);
    padding-inline-end: var(--amplify-components-button-padding-inline-end);
    transition: all var(--amplify-components-button-transition-duration);
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
    --amplify-internal-button-disabled-color: var(--amplify-components-button-disabled-color);
    --amplify-internal-button-disabled-background-color: var(--amplify-components-button-disabled-background-color);
    --amplify-internal-button-disabled-border-color: var(--amplify-components-button-disabled-border-color);
    --amplify-internal-button-disabled-text-decoration: initial;
    --amplify-internal-button-loading-background-color: var(--amplify-components-button-loading-background-color);
    --amplify-internal-button-loading-border-color: var(--amplify-components-button-loading-border-color);
    --amplify-internal-button-loading-color: var(--amplify-components-button-loading-color);
    --amplify-internal-button-loading-text-decoration: initial;
}
```

My guess is first one is out of the question., too much work?
