### DISCUSSION TITLE
"Top Tags"/"Cut Corner" Components

### DISCUSSION THREAD

**Discussion by DerWaffleHousen** [mantinedev/mantine#6005] [Feature requests]
It is a royal pain to create "top tags" (not sure what else to call them).
Things like this:

![image](https://github.com/mantinedev/mantine/assets/165231187/732c4141-3a61-485e-b7ce-1c2179e01def)

It would be nice to have these with:

- Default aesthetic for degree of angle on the side border
- Adjustable size (can be performed by whatever you embed inside it, probably)
- Ability to remove the left or right so that it can be floated to the left or right instead of center like in my example
- Shadow options (Phase 2)

The CSS for this can get nasty and with PostCSS it can be a bit of headache. Having a prebuilt component built into Mantine would be awesome instead of having to create a custom component for it that isn't as robust.

A decent jumping-off point is starting here that is getting me close to where I want:

```css
.myDiv {
  width:             25%;
  margin-left:       auto;
  margin-right:      auto;
  -webkit-clip-path: polygon(0 calc(100% - 15px), 15px 100%, calc(100% - 15px) 100%, 100% calc(100% - 15px), 100% 0, 0 0);
  clip-path:         polygon(0 calc(100% - 15px), 15px 100%, calc(100% - 15px) 100%, 100% calc(100% - 15px), 100% 0, 0 0);
}
```
