### DISCUSSION TITLE
How can I set direction for a single component?

### DISCUSSION THREAD

**Discussion by mohammad-reza-rahbar** [mantinedev/mantine#6334] [Q&A] [answered]
Hello. I could change the direction globally to RTL using [DirectionProvider](https://mantine.dev/styles/rtl/#directionprovider). But there are situations where a component or a part of it must be LTR. For example username and password fields and numbers are almost always LTR.  Now how can I change a TextInput direction (not its label or errors, although it would be nice to change them too) to LTR when the global direction is RTL?

**Comment by atareversei** [comment, marked as answer]
Hi. I do it by defining a global CSS class like:

```css
/* you can target label and error text by using the classNames provided at each component's styles API.
For instance, input style props: https://mantine.dev/core/input/?t=styles-api
Here I am just targeting the input field itself */
.ltr-input .mantine-TextInput-input {
  direction: ltr;
  text-align: left;
}
```

Then, when I need the input to be ltr I just use the className:
```tsx
<TextInput
  className="ltr-input"
  label={l.dash.cust.createCustomerEmailLabel}
  {...form.getInputProps('email')}
/>
```
And the result looks like this:
![image](https://github.com/mantinedev/mantine/assets/76823888/18b16134-1298-46da-9d4f-0c56f2c8e0d4)
