### DISCUSSION TITLE
Changing the style of calendar

### DISCUSSION THREAD

**Discussion by kkpongza** [mantinedev/mantine#6372] [Q&A] [answered]
i want to change the calendar header
from
![image](https://github.com/mantinedev/mantine/assets/120788226/e11f7fd5-cf44-48cb-b1b0-7b65052e79ef)
to
![image](https://github.com/mantinedev/mantine/assets/120788226/edb141c7-4ff0-4009-af88-08e183fe1246)
This is my code

<Calendar
          date={date}
          hideOutsideDates
          // hideWeekdays
          static
          withCellSpacing
          onDateChange={setDate}
          monthLabelFormat={monthLabel}
          
        />
        how can i style it pls help

**Comment by atareversei** [comment, marked as answer]
Target the component with classNames from [styles API](https://mantine.dev/dates/calendar/?t=styles-api). I would suggest creating a wrapper component, and using modularized styles.
```tsx
// Calendar.tsx
import c from './calendar.module.css';

<Calendar
  date={date}
  className={c.calendar}
  // ... other props
/>
```

```css
/* calendar.module.css */
.calendar .mantine-Calendar-calendarHeader {
    display: grid;
    grid-template-columns: 1fr max-content max-content;
}

.calendar .mantine-Calendar-calendarHeaderLevel {
    order: -1;
    justify-self: flex-start;
    padding-inline: var(--mantine-spacing-md);
}
```
Result:
![image](https://github.com/mantinedev/mantine/assets/76823888/cbfb461a-cb52-4e46-9ee5-03f4ce014034)


For the plus button that you have put there in your design, I guess Mantine doesn't provide anything for that so you have to do it manually. You can try hacky things like putting a button up there with position absolute or something but I wouldn't suggest it, simply because Mantine is not supporting it and doing so might break your application when Mantine upgrades to version 8 or something in the future.
