### DISCUSSION TITLE
Input.Group, extend Button.Group to support all input.

### DISCUSSION THREAD

**Discussion by docjyJ** [mantinedev/mantine#6540] [Feature requests]
Hi,

I would like to have something that would allow to create input groups like bootstrap does.

I created a component quickly, but it would be nice if it was included in the library. it already exists for the buttons why not the inputs.

Thanks!

See:
- Button.Group: https://mantine.dev/core/button/#buttongroup
- Number input with currency select: https://ui.mantine.dev/category/inputs/#currency-input
- Bootstrap, Input group: https://getbootstrap.com/docs/5.3/forms/input-group/

```tsx
import { Group, GroupProps } from '@mantine/core';
import './GroupedInputs.css';

export default function GroupedInputs(props: GroupProps) {
  return <Group className="root" gap={0} wrap='nowrap' {...props} />;
}
```
```css
.root> :not(:first-child),
.root> :not(:first-child) .mantine-Input-input {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}

.root> :not(:last-child),
.root> :not(:last-child) .mantine-Input-input {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
  border-right: 0;
}
```
