### DISCUSSION TITLE
Customize text input size in tiptap editor

### DISCUSSION THREAD

**Discussion by bastiengrignon** [mantinedev/mantine#6679] [Q&A] [answered]
I've set a defaultProps size to **md** in the theme object, it is then impacted in the TipTap Editor link editor input to add a new link

But it's not aligned the same as the button obviously (see the image) : 
![image](https://github.com/user-attachments/assets/1fd6c7c9-b6a7-4255-9b4b-26380ca30738)

But I didn't find any way to update this size of the input. I've seen in the Styles API that you can modify the styles of the input with `linkEditorInput` but how can I modify the props of the input directly ? or how can I set CSS styles to modify the input size ?

**Comment by bastiengrignon** [comment, marked as answer]
For other who would came across the same issue I've managed to do it using styles API of the editor and setting multiple CSS variables : 

JSX : 
```jsx
<RichTextEditor
    classNames={{
        linkEditorInput: classes.linkInputContainer,
    }}>
...
</RichTextEditor>

```
CSS : 
```css
.linkInputContainer {
  --input-size: var(--input-height-sm);
  --input-height: var(--input-height-sm);
  --input-fz: var(--mantine-font-size-sm);
}
```

Just don't know if that's the only variable I need or if I'm missing some ! Seems to be fine for the moment
