### DISCUSSION TITLE
add data-error attribute for label element in inputs

### DISCUSSION THREAD

**Discussion by daniel-aziz** [mantinedev/mantine#6872] [Feature requests]
so label can be applied styles as wrapper or input.

**Comment by rtivital** [comment]
You can do that with CSS using :has selector – https://codesandbox.io/p/sandbox/mantine-react-template-forked-xksdg6?file=%2Fsrc%2FApp.tsx%3A6%2C11&workspaceId=dd881b63-29f6-464c-bcdf-b5f78ad65b26

```css
.mantine-InputWrapper-root:has(.mantine-Input-input[data-error]) .mantine-InputWrapper-label {
  background-color: red;
}
```
