### DISCUSSION TITLE
Support for `color` prop on DatePicker

### DISCUSSION THREAD

**Discussion by mattdenkers** [mantinedev/mantine#7221] [Feature requests]
Hi there! First of all, amazing work on Mantine, it's a fantastic library. Everything below is related to version 7.12 btw.

I have a use case where it would be great to have separately themed DatePickers. The default behavior is for selected days to be the theme's primary color, and for days in the range to be a variant of that primary color, etc.

Similar to other Mantine components where it's possible to specify color, i.e. `<Button color="green">Green button</Button>`, my use case would be simplified by being able to specify `<DatePicker color="green">` for example.

Here's an example of my current CSS workaround, where the primary theme color is a shade of purple, and this CSS ensures the datepicker uses custom shades of blue instead:
```css
.blue-datepicker {
    .mantine-DatePicker-day {
        /* Order is important with these */
        &[data-selected] {
            background-color: var(--mantine-color-dvm-blue-filled);
            color: white;
        }

        &[data-in-range] {
            background-color: color-mix(
                in srgb,
                var(--mantine-color-dvm-blue-filled) 20%,
                transparent
            );
            color: black;
        }

        &[data-weekend] {
            color: red;
        }

        &[data-first-in-range] {
            background-color: var(--mantine-color-dvm-blue-filled);
            color: white;
            opacity: 1;
        }

        &[data-last-in-range] {
            background-color: var(--mantine-color-dvm-blue-filled);
            color: white;
            opacity: 1;
        }
    }
}
```

I hope this request makes sense! It's also possible I'm missing something in the docs and there's a simpler workaround - if that's the case, please let me know.

Thank you!
