### DISCUSSION TITLE
Issue with ‍`variant="default"‍` custom border overriding error state in `TextInput`

### DISCUSSION THREAD

**Discussion by shaadcode** [mantinedev/mantine#7680] [Q&A] [answered]
Hi 👋

I'm trying to customize the TextInput component using the default variant. I want the input to have a specific border style when variant="default" — like this:
‍‍
```
.input {
  border-radius: var(--mantine-radius-md);
  &[data-variant="default"] {
    background-color: #f9f9f9;
    border: 1px solid #d1d5db;
  }
}
```

This works fine in the normal state.
However, when the input is invalid (i.e. `data-invalid="true"`), Mantine's built-in error styles (red border) are not being applied — the indigo border stays in place.

I understand Mantine uses internal styles that might override or conflict with these cases, but is there a recommended approach for customizing variant-specific styles while still preserving the error state styling?

**Comment by shaadcode** [comment]
> the indigo border stays in place. ❌
#d1d5db border stays in place. ✅

sorry 🙏

**Comment by rtivital** [comment, marked as answer]
When you do 

```css
.input {
  border-radius: var(--mantine-radius-md);
  &[data-variant="default"] {
    background-color: #f9f9f9;
    border: 1px solid #d1d5db;
  }
}
```

You override input styles with high specificity selector. In this case, you need to add invalid styles on your side.

```css
.input {
  border-radius: var(--mantine-radius-md);
  &[data-variant="default"] {
    background-color: #f9f9f9;
    border: 1px solid #d1d5db;
    
    &[data-error] {
      border-color: var(--mantine-color-error);
    }
  }
}
```
