### DISCUSSION TITLE
Text not inheriting parent Title's font-size

### DISCUSSION THREAD

**Discussion by nickdos** [mantinedev/mantine#7699] [Q&A] [answered]
Using the [example from the docs](https://mantine.dev/core/text/#inherit-styles), I'm getting a different behaviour in my app and I'm not sure what is causing it. I'm running latest version of Mantine (7.17.4).

```jsx
<Title order={3}>Title in which you want to <Text span c="blue" inherit>highlight</Text> something</Title>
```
<img width="630" alt="image" src="https://github.com/user-attachments/assets/4f080c81-1c17-414f-b7eb-2479919571a9" />

In Chrome's inspector I can see the inherit font-size is being overwritten with `1rem`:

<img width="494" alt="image" src="https://github.com/user-attachments/assets/cfd953be-af40-4762-9513-eba5e3dc4a08" />

```css
@media (min-width: 48em) {
    ._root_v4h9i_1 {
        font-size: 1rem;
        line-height: 1.25rem;
    }
}
```

and here's the rendered DOM

```html
<h3 class="_root_hp9ac_1 m_8a5d1357 mantine-Title-root" data-order="3" style="--title-fw: var(--mantine-h3-font-weight); --title-lh: var(--mantine-h3-line-height); --title-fz: var(--mantine-h3-font-size);">Title in which you want to <span class="mantine-focus-auto _root_v4h9i_1 m_b6d8b162 mantine-Text-root" data-inherit="true" style="color: var(--mantine-color-blue-text);">highlight</span> something</h3>
```

Any ideas?

**Comment by nickdos** [comment]
I think I tracked it down to our custom theme, that is being pulled in as a Node dependency. Someone else wrote this and it seems it needs to be improved so it doesn't break styling like this.

```css
/* Desktop Font Sizes */
  @media (min-width: 48em) {
    font-size: 1rem;
    line-height: 1.25rem;

    &[data-size="xl"] {
      font-size: 1.375rem;
      line-height: 1.625rem;
    }
    &[data-size="lg"] {
      font-size: 1.125rem;
      line-height: 1.375rem;
    }
    &[data-size="md"] {
      font-size: 1rem;
      line-height: 1.5rem;
    }
    &[data-size="sm"] {
      font-size: 0.875rem;
      line-height: 1.25rem;
    }
    &[data-size="xs"] {
      font-size: 0.75rem;
      line-height: 1rem;
    }
  }
```

It seems it might be a bad idea to have an undecorated rule like the first one(?). Should it be removed or editted in some way?

**Comment by nickdos** [comment, marked as answer]
This seems to have fixed it but I've not done exhaustive testing to ensure it hasn't broken other parts of the code:

```css
&[data-size="base"] {
  font-size: 0.875rem;
  line-height: 1.125rem;
}
```

Is there a better way to handle this?
