### DISCUSSION TITLE
$mantine-breakpoint-xs Undefined Variable error.

### DISCUSSION THREAD

**Discussion by sstriano** [mantinedev/mantine#7758] [Q&A]
Trying to reference the breakpoints inside sass modules.

**postcss.config.cjs**
```javascript
module.exports = {
  plugins: {
    "postcss-preset-mantine": {},
    "postcss-simple-vars": {
      variables: {
        "mantine-breakpoint-xs": "36em",
        "mantine-breakpoint-sm": "48em",
        "mantine-breakpoint-md": "62em",
        "mantine-breakpoint-lg": "75em",
        "mantine-breakpoint-xl": "88em",
      },
    },
  },
};

``` 

**SCSS File**
```css
.icon {
  background-color: var(--mantine-color-white);
  border-radius: 50%;
  color: var(--mantine-color-blue-6);

  @media (max-width: $mantine-breakpoint-xs) {
    background-color: red;
  }
}

``` 

Produces this error:

```
[sass] Undefined variable.
@media (max-width: $mantine-breakpoint-xs) {
```

Any ideas? Thanks in advance.
