### DISCUSSION TITLE
Can I change the color of the "dimmed" since its a CSS variable?

### DISCUSSION THREAD

**Discussion by nimitnshah** [mantinedev/mantine#7797] [Q&A] [answered]
I can see in the list of CSS variables that "dimmed" is set to "gray-6", is there a way to change it to say "gray-7"? I tried going through the documentation but couldn't find the answer, I found the variable but no way to change it? Am I missing something?

**Comment by rtivital** [comment, marked as answer]
You can change CSS variables by creating a CSS file:

```css
:root {
  @mixin light-root {
    --mantine-color-dimmed: var(--mantine-color-gray-7);
  }

  @mixin dark-root {
    --mantine-color-dimmed: var(--mantine-color-dark-1);
  }
}
```

**Reply by nimitnshah** [reply]
Thank you so much for the prompt response! I think I finally understand how to fully theme Mantine :) I think just edit the second one to be "dark-root" so its fully working?

**Reply by rtivital** [reply]
Yes, that was a mistake, I've corrected it

**Reply by nimitnshah** [reply]
I have another question. I was trying to change the borders of all components (cards, popovers, select, etc.) but when I changed the `--mantine-color-default-border`, the changes aren't applying? I understand I can extend a particular component background, for example I was able to change the background of all cards by taking the theme objecting and passing default props, but if I wanted to change border for components, how would I? I could pass default props in those components one by one, but I was wondering if there was one place centrally where I could change it, and the changes would reflect everywhere?

**Reply by rtivital** [reply]
In css file:

```scss
[class^=mantine] {
  --mantine-color-default-border: red !important;
}
```
