### ISSUE TITLE
Cross-site Scripting in quill

### ISSUE THREAD

**Issue by hckhanh** [mantinedev/mantine#2870]
### What package has an issue

@mantine/rte

### Describe the bug

I got the security report from `quill` package which is used by deps of @mantine/rte (maybe react-quill or quill-mention)

```
"@mantine/rte@npm:5.6.3":
  version: 5.6.3
  resolution: "@mantine/rte@npm:5.6.3"
  dependencies:
    "@tabler/icons": ^1.68.0
    quill-mention: ^3.0.8
    react-quill: 2.0.0
  peerDependencies:
    "@mantine/core": 5.6.3
    "@mantine/hooks": 5.6.3
    react: ">=16.8.0"
    react-dom: ">=16.8.0"
  checksum: 9ffa82ce53871e879c7c58ba95a2e266d705f866b256181c19a785b1a82995c0b6bc7fd4be9b7c22df870acd0e92a1de80e02176c632bf72a2f9b30d36f1c875
  languageName: node
  linkType: hard
```

### What version of @mantine/hooks page do you have in package.json?

5.6.3

### Possible fix

Please check the issue at: https://github.com/quilljs/quill/issues/3364

![image](https://user-images.githubusercontent.com/6380436/199651023-344e985a-3b98-4930-81ea-723425f32ece.png)
