### ISSUE TITLE
table tbody th

### ISSUE THREAD

**Issue by dejurin** [mantinedev/mantine#3501]
### What package has an issue

@mantine/core

### Describe the bug

<img width="381" alt="Screenshot 2023-02-06 at 04 24 28" src="https://user-images.githubusercontent.com/4470015/216868956-e5b8a8f4-9186-4e91-86e4-69fe910c4629.png">

If to use **TH** in the **TBODY** I got incorrect style of cells.

**Fix**
<img width="327" alt="Screenshot 2023-02-06 at 04 35 10" src="https://user-images.githubusercontent.com/4470015/216870351-71eb641b-3c4e-46bf-a33b-fc58dd77a114.png">

This HTML approach lets in and is often used.

<img width="789" alt="Screenshot 2023-02-06 at 04 38 06" src="https://user-images.githubusercontent.com/4470015/216870768-8813faa2-dd76-40da-9fd6-e46ce9ab00a6.png">
**More**: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody

### What version of @mantine/hooks page do you have in package.json?

5.10.3

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

**Edit**: _Table.styles.ts_

Add to selector **"& tbody tr th"**
```CSS
 '& thead tr th, & tfoot tr th, & tbody tr th': {
          textAlign: 'left',
          fontWeight: 'bold',
          color: theme.colorScheme === 'dark' ? theme.colors.dark[0] : theme.colors.gray[7],
          fontSize: theme.fn.size({ size: fontSize, sizes: theme.fontSizes }),
          padding: `${theme.fn.size({
            size: verticalSpacing,
            sizes: theme.spacing,
          })}px ${theme.fn.size({ size: horizontalSpacing, sizes: theme.spacing })}px`,
        },

        '& tfoot tr th, & tbody tr th': {
          borderTop: border,
        },

```
**Add new**
```CSS
        '& tbody tr th': {
          borderRight: withColumnBorders ? border : 'none',
        },
```
