### ISSUE TITLE
CSS styles does not work without adding !important

### ISSUE THREAD

**Issue by melihcoban** [mantinedev/mantine#6109]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Edge

### Describe the bug

I am migrating from Mantine v6 to v7.

I upgraded all mantine packages to latest version, added postcss dependencies and created postcss.config.cjs file in the root folder. I added ```import '@mantine/core/styles.css';``` to my entry file. However, if I do not add !important to css modules my styles are not applied.

```tsx

import classes from './SubSidebar.module.css';

function SubSidebar() {

// state definitions

  const items = (hasLinks ? subItems : []).map(link => (
    <Text
      className={classes.link}
      data-active={link.label === activeSubMenu || undefined}
      key={link.label}
      onClick={event => handleChevronClick(event, link.route, link.label)}>
      {`${t(link.label)}`}
    </Text>
  ));
}
```

```css
.link {
    font-weight: 500 !important;
    display: 'block' !important;
    text-decoration: 'none' !important;
    padding: var(--mantine-spacing-xs) var(--mantine-spacing-md) !important;
    padding-left: 31rem;
    margin-left: 30rem;
    font-size: var(--mantine-font-size-sm) !important;
    color: light-dark(var(--mantine-color-gray-7), var(--mantine-color-dark-0)) !important;
    border-left: 1px solid light-dark(var(--mantine-color-gray-3), var(--mantine-color-dark-4)) !important;

    @mixin hover {
    color: light-dark(var(--mantine-color-black), var(--mantine-color-black)) !important;
  }

  &[data-active] {
    color: var(--mantine-color-blue-light-color);
  }
}
```

### Self-service

- [ ] I would be willing to implement a fix for this issue
