### ISSUE TITLE
When Combobox.Search is used with ScrollArea, it will exceed the boundary.

### ISSUE THREAD

**Issue by minosss** [mantinedev/mantine#6562]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When Combobox.Search is used with ScrollArea, it will exceed the boundary. Because the search input set width style `calc(100% + var(--combobox-padding) * 2)`. However, there is no processing done when there are ScrollArea.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/icy-snow-5g2f6m

### Possible fix

Reset width when there are has ScrollArea

```css
.mantine-Combobox-dropdown:has([data-mantine-scrollbar]) .mantine-Combobox-search {
  width: calc(100% + var(--combobox-padding));
}
```

### Self-service

- [ ] I would be willing to implement a fix for this issue
