### ISSUE TITLE
Nested table heading row applies incorrect border/background style

### ISSUE THREAD

**Issue by andrewborstein** [mantinedev/mantine#7354]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.3

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When a table is nested inside another table, some `tr` styling can be incorrectly applied to the nested table. 
- bottom row border is not applied
- striped background color is mistakenly applied

![Screenshot 2025-01-13 at 3 19 28 PM](https://github.com/user-attachments/assets/bf91b30e-b9f6-4f77-a6d5-bcd11d22c38e)

### If possible, include a link to a codesandbox with a minimal reproduction

https://stackblitz.com/edit/vitejs-vite-gk5j2tm4?file=src%2FApp.tsx

### Possible fix

It looks like the issue arises in [this block of `Table.module.css` code](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/components/Table/Table.module.css#L76-L94).

The `last-of-type` and `nth-of-type` styles are both applied to all descendants of `.tbody` which in this case means all `tr` that are direct children and the children of nested tables (and thus nested `.tbody` elements). 

If the styles were instead applied only to `tr` that are direct children of `tbody`, the style issue would be resolved. 

So instead of 

```css
.tbody {
  & :where(tr) {
```

it would be

```css
.tbody {
  & > tr {
```

I've demonstrated the potential fix in [the linked sandbox](https://stackblitz.com/edit/vitejs-vite-gk5j2tm4?file=src%2FApp.tsx), using plain CSS. I haven't developed Mantine locally before, so haven't tried the fix in the source code yet.

In my local application I'm using these CSS modules styles to manually patch the bug

`table.module.css`
```css
/* BEGIN CSS FIX - https://github.com/mantinedev/mantine/issues/7354 -------- */
/* 
 * Row Borders
 * - Force all bottom row borders to be set
 * - Remove bottom borders only on the last tr that's a direct child of a tbody, not all descendant tr  
 */
.table tr:where([data-with-row-border]) {
  border-bottom: 1px solid var(--table-border-color);
}
.table tbody > tr:where([data-with-row-border]:last-of-type) {
  border-bottom: none;
}

/* 
 * Striped Rows
 * - Force all tr backgrounds to be white
 * - Remove bottom borders only on the last tr that's a direct child of a tbody, not all descendant tr  
 */
.table tbody tr:where([data-striped='odd']) {
  background-color: transparent;
}
.table tbody > tr:where([data-striped='odd']:nth-of-type(odd)) {
  background-color: var(--table-striped-color);
}
/* END CSS FIX -------------------------------------------------------------- */
```

```tsx
import { Table } from '@mantine/core'
import styles from './table.module.css'

export SomeTableComponent = () => {
  return (
    <Table className={styles.table}>
      {/* ... */}
    <Table>
  )
}
```

### Self-service

- [X] I would be willing to implement a fix for this issue
