### ISSUE TITLE
When using stickyHeader with withTableBorder and withColumnBorders, border sometimes shows up and sometimes doesn't

### ISSUE THREAD

**Issue by WojakGra** [mantinedev/mantine#7593]
### Dependencies check up

- [x] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.17.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

If I have everything added, sometimes the border on the header shows and sometimes it doesn't. When resizing the window, you can see that it blinks this border at the header as well as the border of the whole table. If there is no stickyHeader then the error does not occur

![Image](https://github.com/user-attachments/assets/a4a5f41b-199c-4708-ac3f-5c466660cec7)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/dq7p39

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by WojakGra** [comment]
If i make a change to css of table it works but there is a still broken when i add `withTableBorder`
```CSS
.thead {
  top: var(--table-sticky-header-offset, 0);
  z-index: 3;

  &:where([data-sticky]) {
    position: sticky;

    & .th {
      position: sticky;
      top: var(--table-sticky-header-offset, 0);
      background-color: var(--mantine-color-body);

      &:after {
        position: absolute;
      }
    }
  }
}
```
